version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
      - .:/workspace
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    networks:
      - wp-network

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    networks:
      - wp-network

volumes:
  wordpress_data:
  db_data:

networks:
  wp-network:
